"""
Django settings for backend_p project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# The environment is the only source (.env locally, Render env vars in
# production). There is deliberately no fallback: a missing key fails loudly
# at startup rather than signing sessions with a value committed to git.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    raise ImproperlyConfigured(
        'DJANGO_SECRET_KEY is not set. Generate one with '
        '`python manage.py shell -c "from django.core.management.utils '
        'import get_random_secret_key; print(get_random_secret_key())"`.'
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# Only the hosts we actually answer on. '*' accepted any Host header, which
# lets an attacker poison absolute URLs the app builds from the request.
ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get(
        'DJANGO_ALLOWED_HOSTS',
        'portfolio-backend-g68o.onrender.com,localhost,127.0.0.1',
    ).split(',')
    if host.strip()
]



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "https://portfolio-frontend-7qkq4q1fk-shubham-s-projects-b0658d3e.vercel.app",
    "https://portfolio-frontend-six-self.vercel.app",
]

# Local development. The Vite dev server takes whatever port is free (8080,
# 8081, 8082 ...), so match any localhost port rather than pinning one —
# without this the browser blocks every call from a dev build, which is what
# left the chatbot and the contact form silently dead locally.
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^http://localhost:\d+$",
    r"^http://127\.0\.0\.1:\d+$",
]

ROOT_URLCONF = 'backend_p.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend_p.wsgi.application'

# This setting informs Django of the URI path from which your static files will be served to users
# Here, they well be accessible at your-domain.onrender.com/static/... or yourcustomdomain.com/static/...
STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'



# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# --- Contact form notifications ----------------------------------------------
# Credentials come from the environment only; .env is gitignored and Render
# supplies these as env vars. For Gmail this must be an App Password, not the
# account password.
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_TIMEOUT = 15

# Where enquiries land.
CONTACT_NOTIFY_EMAIL = os.environ.get('CONTACT_NOTIFY_EMAIL', 'shubhh1012@gmail.com')
DEFAULT_FROM_EMAIL = os.environ.get(
    'DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'portfolio@localhost'
)

# Without credentials, print the message to the server log instead of failing
# to connect — so local development still exercises the whole path.
EMAIL_IS_CONFIGURED = bool(EMAIL_HOST_USER and EMAIL_HOST_PASSWORD)
EMAIL_BACKEND = (
    'django.core.mail.backends.smtp.EmailBackend'
    if EMAIL_IS_CONFIGURED
    else 'django.core.mail.backends.console.EmailBackend'
)

if not EMAIL_IS_CONFIGURED:
    # Say so, loudly and on stderr. This fallback is a convenience locally and a
    # silent outage in production: enquiries get printed to the log, the API
    # still answers 200, and nobody finds out until someone asks why they never
    # heard back. Logging is not configured this early, so write directly.
    _missing = [
        name
        for name, value in (
            ('EMAIL_HOST_USER', EMAIL_HOST_USER),
            ('EMAIL_HOST_PASSWORD', EMAIL_HOST_PASSWORD),
        )
        if not value
    ]
    sys.stderr.write(
        "\n"
        "*** CONTACT EMAIL IS NOT BEING SENT ***\n"
        f"    Missing: {', '.join(_missing)}\n"
        "    Enquiries will be printed to this log instead of delivered, and\n"
        "    /api/contact/ will report \"notified\": false.\n"
        "    Set these on the Render service (or in .env locally) and restart.\n"
        "    Gmail needs a 16-character App Password, not the account password.\n"
        "\n"
    )
